core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index,name='index'),
]

tweets/urls.py
from django.conf.urls import url
from . import views

urlpatterns= [

 url(r'^$',views.tweet_list,name='tweet_list'),
 url(r'^tweets/(?P<id>\d+)/$',views.tweet_detail,name='tweet_detail'),
 url(r'^new/$',views.tweet_new,name='tweet_new'),
 url(r'^tweet/(?P<id>\d+)/edit/$',views.tweet_edit,name='tweet_edit'),
 url(r'^tweet/(?P<id>\d+)/delete/$',views.tweet_delete,name='tweet_delete'),
 url(r'^tweet/(?P<id>\d+)/retweet/$',views.retweet,name='retweet'),
]

twitter_clone/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^tweets/',include('tweets.urls',namespace='tweets')),
    url(r'^',include('core.urls',namespace = 'core')),
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
 url(r'^$',views.user_list,name='user_list'),
 url(r'^(?P<id>\d+)/$',views.user_detail,name='user_detail'),
 url(r'^new/$',views.user_new,name='user_new'),
 url(r'^user/(?P<id>\d+)/edit$',views.user_edit,name='user_edit'),
 url(r'^user/(?P<id>\d+)/follow$',views.follow,name='follow'),
 url(r'^user/(?P<id>\d+)/unfollow$',views.unfollow,name='unfollow'),
 url(r'^user/tweet_new$',views.tweet_new,name='tweet_new'),
 url(r'^user/(?P<id>\d+)/tweet_edit$',views.tweet_edit,name='tweet_edit'),
 url(r'^user/(?P<id>\d+)/tweet_delete$',views.tweet_delete,name='tweet_delete'),
]

tweets/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime


class Tweet(models.Model):
    heading = models.CharField(max_length =50)
    content = models.CharField(max_length=140,blank = True)
    hashtag = models. CharField(max_length=20,blank= True)
    posted_on = models.DateField(auto_now_add=True)
    profile = models.ForeignKey('users.Profile',null=True)
    retweet = models.CharField(max_length=140,blank=True)


    def __str__(self):
        return self.heading

tweets/forms.py
from django import forms
from .models import Tweet
from core.forms import BootstrapFormMixin


class  TweetForm(BootstrapFormMixin,forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ('heading','content','hashtag',)

class  RetweetForm(BootstrapFormMixin,forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ('retweet',)

tweets/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
from .models import Tweet
from .forms import TweetForm,RetweetForm
from django.contrib import messages
from users.models import Profile

def base_context(request,id):
    tweets = Tweet.objects.all()
    tweet = get_object_or_404(Tweet, pk=id)
    profile = tweet.profile
    current_profile = request.user.profile
    follows = profile.get_following()
    follows = follows.exclude(user = profile.user)
    follower = profile.get_followers()
    follower = follower.exclude(user= profile.user)
    context = {
        "tweets": tweets,
        "profile_tweet": tweet,
        "current_profile":current_profile,
        "profile":profile,
        "follower":follower,
        "follows":follows,
        "user" : request.user
    }
    return context


def tweet_list(request,id):
    context = base_context(request,id)
    return render(request,"tweets/tweet_list.html",context)

def tweet_detail(request, id):
    
    context = base_context(request,id)
    return render(request, "tweets/tweet_detail.html", context)


def tweet_new(request):

    context = base_context(request,id=1)
    if request.method == "POST":
        form = TweetForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.profile = request.user.profile
            tweet.save()
            messages.success(request,"tweet created!")
            return redirect("users:user_detail", id=current_profile.pk)
    else:
        form =TweetForm()

    context["form"] =form 

    return render(request,"tweets/tweet_edit.html", context)



def tweet_edit(request,id):
    current_profile = request.user.profile
    tweet = get_object_or_404(Tweet, pk=id)
    if request.method == "POST":
        form = TweetForm(request.POST, instance=tweet)
        if form.is_valid():
            tweet = form.save()
            messages.success(request, "{} has been updated!".format(tweet.heading))
            return redirect("users:user_detail", id=current_profile.pk)
    else:
        form = TweetForm(instance=tweet)

    context = {
        "form": form,
        "tweet": tweet,
        "current_profile":current_profile,
        }
    return render(request, "tweets/tweet_edit.html",context)

def retweet(request,id):
    tweet = get_object_or_404(Tweet, pk=id)
    if request.method == "POST":
        form = RetweetForm(request.POST, instance=tweet)
        if form.is_valid():
            tweet = form.save()
            messages.success(request,"Done!")
            return redirect("users:user_detail", id=current_profile.pk)
    else:
        form = TweetForm(instance=tweet)

    context = {
        "form": form,
        "tweet": tweet,
        }
    return render(request, "tweets/tweet_edit.html",context)

def tweet_delete(request,id):
    current_profile = request.user.profile
    if request.method == "POST":
        tweet = get_object_or_404(Tweet, pk=id)
        tweet.delete()
        messages.success(request, "Tweet deleted!")
        return redirect("users:user_detail", id=current_profile.pk)
    else:
        messages.success(request, "Tweet not found!")
        return redirect("users:user_detail", id=current_profile.pk)

tweets/templates/tweets/tweet_detail.html
<div class="panel panel-default">
Create New Tweet
    <div class="pull-right">
        <a href="{% url 'users:tweet_new' %}">
            <i class="fa fa-plus-square"></i>
        </a>
    </div>
</div>
{% for tweet in user_profile.tweet_set.all %}
<div class="card card-inverse card-primary text-xs-center">
    <div class="container">
        <div class="card-block" id="card-block">
            <h4 class="card-title">
                {{tweet.heading}}
                    <a href="{% url 'users:tweet_edit' tweet.pk %}">
                        <i class="fa fa-pencil-square" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'users:tweet_delete' tweet.pk %}">
                        <i class="fa fa-minus-square" aria-hidden="true"></i>
                    </a>
            </h4>
            <blockquote class="card-blockquote">
                <p>{{tweet.content}}</p>
                <footer>
                    Posted by: {{tweet.profile.user.username}}
                    Posted on:{{tweet.posted_on}}
                </footer>
            </blockquote>
        </div>
        <div class="card-block" id="card-block">
            <img class="responsive" src="{{tweet.profile.profile_pic}}">
        </div>
    </div>
    <hr>
</div>
{% endfor %}

tweets/templates/tweets/tweet_edit.html
{% extends "core/base.html" %}
{% block user-content %}
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default profile_block">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4">
                            <img class="img-thumbnail profile_pic" src="{{current_profile.profile_pic}}" alt="Profile Pic">
                        </div>
                        <div class="col-md-8">
                            <div class="row">
                                {{current_profile.user.username}}
                                {{current_profile.bio}}
                            </div>
                            <div class="row">
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row profile">
                <div class="col-md-12">
                    <div class="col-md-4 ">
                    Tweets
                    </div>
                    <div class="col-md-4">
                        Following
                    </div>
                    <div class="col-md-4">
                        Followers
                    </div>
                    <hr>
                </div>
            </div>
            <div class="row profile">
                <div class="col-md-12">
                    <div class="col-md-4">
                    {{current_profile.tweet_set.count}}
                    </div>
                    <div class="col-md-4">
                        {{current_profile.following.count}}
                    </div>
                    <div class="col-md-4">
                        {{current_profile.followed_by.count}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <h5>Following</h5>
                {% for a in follows %}
                {% if a %}
                        <a href="{% url 'users:user_detail' a.pk%}" >
                            <img class="img-thumbnail profile_pic" src="{{a.profile_pic}}">
                        </a>
                {% endif %}
                {% endfor %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <h5>Followers</h5>
                {% for a in follower %}
                {% if a %}
                        <a href="{% url 'users:user_detail' a.pk%}" >
                            <img class="img-thumbnail profile_pic" src="{{a.profile_pic}}">
                        </a>
                {% endif %}
                {% endfor %}
        </div>
    </div>
</div>
{% endblock user-content%}


{% block tweet-content %}
<div class="row">
    <div class="col-md-12">
        <div class="nav color">
            <h2>
            Tweet column
                <div class="pull-right">
                    <a href="{% url 'tweets:tweet_new' %}">
                        <i class="fa fa-plus-square" aria-hidden="true"></i>
                    </a>
                </div>
            </h2>
        </div>
    </div>
</div>
{% if tweet %}
<h2>
    Edit:{{tweet.name}}
</h2>
{% else %}
<h2>
    New Tweet
</h2>
{% endif %}


<form action="" method="POST">
    {% csrf_token %}
    
    {% for field in form %}
    {% include "core/_form_input.html" %}
    {% endfor %}

    <button type="submit" class="btn btn-primary btn-block btn-lg">
        Save
    </button>
</form>

{% endblock tweet-content %}

tweets/templates/tweets/tweet_list.html
<div class="panel panel-default">
Create New Tweet
    <div class="pull-right">
        <form action ="{% url 'users:tweet_new' %}" method="POST">
        {% csrf_token %}
            <button class="btn btn-primary btn-xs">
                <i class="fa fa-plus-square"></i>
            </button> 
        </form>
    </div>
</div>
{% for tweet in tweets %}
<div class="card card-inverse card-primary text-xs-center">
    <div class="container">
        <div class="card-block" id="card-block">
            <h4 class="card-title">
                {{tweet.heading}}
                {% if tweet.profile == current_profile %}
                    <a href="{% url 'users:tweet_edit' tweet.pk %}">
                        <i class="fa fa-pencil-square" aria-hidden="true"></i>
                    </a>
                    <a href="{% url 'users:tweet_delete' tweet.pk %}">
                        <i class="fa fa-minus-square" aria-hidden="true"></i>
                    </a>
                {% endif %}
            </h4>
            <blockquote class="card-blockquote">
                <p>{{tweet.content}}</p>
                <footer>
                    Posted by: {{tweet.profile.user.username}}
                    Posted on:{{tweet.posted_on}}
                </footer>
            </blockquote>
        </div>
        <div class="card-block" id="card-block">
            <img class="responsive" src="{{tweet.profile.profile_pic}}">
        </div>
    </div>
    <hr>
</div>
{% endfor %}