accounts/urls.py
from django.conf.urls import url
from .forms import LoginForm
from . import views

urlpatterns = [
    url(r'^register/$',views.register, name = 'register'),
    url(r'^login/$','django.contrib.auth.views.login',{'authentication_form':LoginForm}, name='login'),
    url(r'^logout/$','django.contrib.auth.views.logout',{'template_name': 'accounts/logout.html'}, name='logout'),
]

core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index,name='index'),
]

twitter_clone/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^tweets/',include('tweets.urls',namespace='tweets')),
    url(r'^',include('core.urls',namespace = 'core')),
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
 url(r'^$',views.user_list,name='user_list'),
 url(r'^(?P<id>\d+)/$',views.user_detail,name='user_detail'),
 url(r'^new/$',views.user_new,name='user_new'),
 url(r'^user/(?P<id>\d+)/edit$',views.user_edit,name='user_edit'),
 url(r'^user/(?P<id>\d+)/follow$',views.follow,name='follow'),
 url(r'^user/(?P<id>\d+)/unfollow$',views.unfollow,name='unfollow'),
 url(r'^user/tweet_new$',views.tweet_new,name='tweet_new'),
 url(r'^user/(?P<id>\d+)/tweet_edit$',views.tweet_edit,name='tweet_edit'),
 url(r'^user/(?P<id>\d+)/tweet_delete$',views.tweet_delete,name='tweet_delete'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django.forms import widgets


class BootstrapFormMixin(object):
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)

        for field in self.fields.values():
            if (isinstance(field.widget, widgets.TextInput)or
                isinstance(field.widget, widgets.Textarea)or
                isinstance(field.widget,widgets.SelectDateWidget)):

                field.widget.attrs.update({
                    "class": "form-control",
                    })

core/views.py
from django.shortcuts import render



def index(request):

    
    return render(request,"core/index.html")


def home(request):

    
    return render(request,"core/home.html")

core/templates/core/_form_input.html
<div 
    {% if field.errors %}
        class="form-group has-error"
    {% else %} 
        class="form-group"
    {% endif %}>
    
        {{field.label_tag}}
        {{field}}

    {% if field.errors %}
        <span class="help-block">
    {% for error in field.errors%}
        {{error}}
    {% endfor %}
        </span>
    {% endif %}
</div>

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        {% block title %}
            Twitter Clone
        {% endblock title %}
    </title>
    <!-- bootswatch theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/cerulean/bootstrap.min.css" >


    <script src="https://use.fontawesome.com/a04d9e4c1c.js"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}" />
</head>
<body>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'users:user_list' %} " class="navbar-brand">
                    <i class="fa fa-home" aria-hidden="true">Home</i>
                </a>
                <a href="{% url 'users:user_list' %} " class="navbar-brand">
                    <i class="fa fa-bell" aria-hidden="true">Notifications</i>
                </a>
                <a href="{% url 'users:user_list' %} " class="navbar-brand">
                    <i class="fa fa-envelope" aria-hidden="true">Messages</i>
                </a>
                <a href="{% url 'users:user_list' %} " class="navbar-brand">
                    <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
            </div>

            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <form class="navbar-form navbar-left" role="search" action= "{% url 'users:user_list' %}">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Find user" name="q">
                        </div>
                        <button class="btn btn-default">Search</button>
                    </form>
                    {% if request.user.is_authenticated %}
                    <li><a href="{% url 'users:user_edit' request.user.pk %}">Hello, {{request.user.username}}</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a> </li>
                    {% else %} 
                    <li><a href="{% url 'accounts:login' %}">Login</a> </li> 
                    <li><a href="{% url 'accounts:register' %}">Sign Up</a> </li> 
                    {% endif %} 

                </ul>
            </div>
        </div>
    </nav>
{% block content%}

{% endblock %}
    <div class="container">
        <div class="profile-content">
        <div class="{% block content_classes %}main-content{% endblock content_classes%}">
            {% if messages %}
            {% for message in messages %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% endif %}
        </div>
        
            <div class="content">
                {% block profile-content %}
                    
                {% endblock profile-content%}
            </div>
            
        </div>
        <div class="tweet-content">
            <div class="content">
                {% block tweet-content %}
                  
                {% endblock tweet-content%}
            </div>
            
        </div>
        <div class="users-content">
            <div class="content">
                {% block users-content %}
                  
                {% endblock users-content%}
            </div>
            
        </div>
    </div>
    <footer class="page-footer">
        <hr>
        <div class="container">
            &copy; Awesome Inc U. Bootcamp 2016
        </div>
    </footer>

<script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block content %}
    <div class="main">
        <div class="left-main">
            <img src="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcS1-qyEE-b1wMCom8lEOnC6bPoceDVTad_lNEAaP_9ZmViUkUAF" alt="">
        </div>
        <div class="right-main">
            <h2>
                Login to enter
            </h2>
            <a href="{% url 'accounts:login' %}">
                <button type="submit" class="btn btn-primary">Login
                </button>
            </a> 
        </div>
    </div>
{% endblock content %}