core/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index,name='index'),
]

twitter_clone/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls',namespace='accounts')),
    url(r'^users/',include('users.urls',namespace='users')),
    url(r'^tweets/',include('tweets.urls',namespace='tweets')),
    url(r'^',include('core.urls',namespace = 'core')),
]

users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
 url(r'^$',views.user_list,name='user_list'),
 url(r'^(?P<id>\d+)/$',views.user_detail,name='user_detail'),
 url(r'^new/$',views.user_new,name='user_new'),
 url(r'^user/(?P<id>\d+)/edit$',views.user_edit,name='user_edit'),
 url(r'^user/(?P<id>\d+)/follow$',views.follow,name='follow'),
 url(r'^user/(?P<id>\d+)/unfollow$',views.unfollow,name='unfollow'),
 url(r'^user/tweet_new$',views.tweet_new,name='tweet_new'),
 url(r'^user/(?P<id>\d+)/tweet_edit$',views.tweet_edit,name='tweet_edit'),
 url(r'^user/(?P<id>\d+)/tweet_delete$',views.tweet_delete,name='tweet_delete'),
]

tweets/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime


class Tweet(models.Model):
    heading = models.CharField(max_length =50)
    content = models.CharField(max_length=140,blank = True)
    hashtag = models. CharField(max_length=20,blank= True)
    posted_on = models.DateField(auto_now_add=True)
    profile = models.ForeignKey('users.Profile',null=True)
    retweet = models.CharField(max_length=140,blank=True)


    def __str__(self):
        return self.heading

users/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

RELATIONSHIP_FOLLOWING = 1
RELATIONSHIP_BLOCKED = 2
RELATIONSHIP_STATUSES = (
    (RELATIONSHIP_FOLLOWING, 'Following'),
    (RELATIONSHIP_BLOCKED, 'Blocked'),
)

class Profile(models.Model):
    user = models.OneToOneField(User)
    bio = models.CharField(max_length=200,blank = True)
    location = models. CharField(max_length=100,blank= True)
    birthday = models.DateField(blank=True)
    profile_pic= models.CharField(max_length=200,blank=True,default = "http://i164.photobucket.com/albums/u8/hemi1hemi/COLOR/COL9-6.jpg")
    relationships = models.ManyToManyField('self',through ="Relationship",symmetrical=False,related_name='related_to',)

    def __str__(self):

        return self.user.username

    def add_relationship(self, profile, status):
        relationship, created = Relationship.objects.get_or_create(
            following=self,
            followed_by=profile,
            status=status)
        return relationship

    def remove_relationship(self, profile, status):
        Relationship.objects.filter(
            following=self,
            followed_by=profile,
            status=status).delete()
        return 

    def get_relationships(self, status):
        return self.relationships.filter(
            followed_by__status=status,
            followed_by__following=self)

    def get_related_to(self, status):
        return self.related_to.filter(
            following__status=status,
            following__followed_by=self)

    def get_following(self):
        return self.get_relationships(RELATIONSHIP_FOLLOWING)

    def get_followers(self):
        return self.get_related_to(RELATIONSHIP_FOLLOWING)




class Relationship(models.Model):
    following = models.ForeignKey(Profile, related_name='following')
    followed_by = models.ForeignKey(Profile, related_name='followed_by')
    status = models.IntegerField(choices=RELATIONSHIP_STATUSES)


    

users/forms.py
from django import forms
from .models import Profile
from core.forms import BootstrapFormMixin
from django.http import HttpRequest



class UserForm(BootstrapFormMixin,forms.ModelForm):

    class Meta:
        model = Profile
        exclude=['user']
        fields = ('bio','location','birthday','profile_pic',)

users/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.db.models import Count
from django.contrib  import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models import Q
from .models import Profile,RELATIONSHIP_STATUSES,Relationship
from .forms import UserForm
from tweets.forms import TweetForm
from tweets.models import Tweet

def base_context(request):
    
    profiles = Profile.objects.exclude(user = request.user)
    current_profile = request.user.profile
    tweets= Tweet.objects.all()
    follows = current_profile.get_following()
    follows = follows.exclude(user = current_profile.user)
    follower = current_profile.get_followers()
    follower = follower.exclude(user= current_profile.user)
    followed_profiles = [following.followed_by for following in current_profile.following.all()]

    context = {
    "profiles": profiles,
    "tweets":tweets,
    "current_profile":current_profile,
    "follower":follower,
    "follows":follows,
    "followed_profiles":followed_profiles,
    }
    return context

@login_required
def user_list(request):
    context = base_context(request)
    query_set = Tweet.objects.all()

    query = request.GET.get('q')
    if query:
        tweets = Tweet.objects.filter(heading__icontains=query)
        query_set = query_set.filter(
            Q(heading__icontains=query) |
            Q(content__in=tweets)
        )
        query_set = query_set.distinct()

    tweets = query_set
    context["tweets"] = tweets
    return render(request,"users/user_list.html",context)


def user_detail(request,id):
    context = base_context(request)
    user_profile = get_object_or_404(Profile,pk=id)
    context["user_profile"] = user_profile
    context["user_tweets"] = user_profile.tweet_set.all()
    return render(request,"users/user_detail.html",context)

def user_new(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.user = request.user
            user.save()
            messages.success(request,"Welcome!")
            return redirect("users:user_detail", id = user.pk)
    else:
        form =UserForm()

    context = {
    "form": form
    }
    return render(request,"users/user_edit.html", context)

def user_edit(request,id):
    # user = get_object_or_404(Profile, pk=id)
    try:
        # import pdb; pdb.set_trace()
        user= User.objects.get(pk=id).profile
        
    except:
        return redirect("users:user_new")

    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            messages.success(request, "{} profile has been updated!".format(user.user.username))
            return redirect("users:user_detail", id=user.pk)
    else:
        form = UserForm(instance=user)

    context = {
        "form": form,
        "user": user,
    }
    return render(request, "users/user_edit.html", context)

def follow(request,id):
    context = base_context(request)
    if request.method == "POST":
        member= Profile.objects.get(pk=id)
        request.user.profile.add_relationship(member,1)
        request.user.save()
        member.save()
        messages.success(request,"Success")
        return render(request,"users/user_list.html",context)

def unfollow(request,id):
    context = base_context(request)
    if request.method == "POST":
        member= Profile.objects.get(pk=id)
        request.user.profile.remove_relationship(member,1)
        request.user.save()
        member.save()
        messages.success(request,"Successfully removed")
        return render(request,"users/user_list.html",context)

def tweet_new(request):
    context = base_context(request)
    if request.method == "POST":
        form = TweetForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.profile = request.user.profile
            tweet.save()
            messages.success(request,"tweet created!")
            return redirect("users:user_detail", id=request.user.profile.pk)
    else:
        form =TweetForm()

    context["form"] =form 

    return render(request,"tweets/tweet_edit.html", context)



def tweet_edit(request,id):
   
    current_profile = request.user.profile
    tweet = get_object_or_404(Tweet, pk=id)
    if request.method == "POST":
        form = TweetForm(request.POST, instance=tweet)
        if form.is_valid():
            tweet = form.save()
            messages.success(request, "{} has been updated!".format(tweet.heading))
            return redirect("users:user_detail", id=current_profile.pk)
    else:
        form = TweetForm(instance=tweet)

    context = {
        "form": form,
        "tweet": tweet,
        "current_profile":current_profile,
        }
    return render(request, "tweets/tweet_edit.html",context)

def tweet_delete(request,id):
    current_profile = request.user.profile
    if request.method == "POST":
        tweet = get_object_or_404(Tweet, pk=id)
        tweet.delete()
        messages.success(request, "Tweet deleted!")
        return redirect("users:user_detail", id=current_profile.pk)
    else:
        tweet = get_object_or_404(Tweet, pk=id)
        tweet.delete()
        messages.success(request, "Tweet deleted!")
        return redirect("users:user_detail", id=current_profile.pk)

users/templates/users/other_users.html
<h4>New Tweet users</h4>
{% for profile in profiles %}
<div class="card">
    <div class="card-block">
        <h4 class="card-title">
            {{profile.user.username}}
        </h4>
        <h6 class="card-subtitle text-muted">
            Support card subtitle
        </h6>
    </div>
        <img class="responsive" src="{{profile.profile_pic}}" alt="Card image">
    <div class="card-block">
        <p class="card-text">
            {{profile.bio | truncatechars:25}}
        </p>
        <a href="{% url 'users:user_detail' profile.user.pk%}" class="card-link">
            View Profile
        </a>
        {% if profile in followed_profiles %}
        <form action="{% url 'users:unfollow' profile.pk %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-primary btn-xs">Unfollow</button>
        </form>
        {% else %}
        <form action="{% url 'users:follow' profile.pk %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-primary btn-xs">Follow</button>
        </form>
        {% endif %}
    </div>
</div>
<hr>
{% endfor %}

users/templates/users/profile_block.html
<div class="card ">
    <div class="card-block">
        <h4 class="card-title">
            {{current_profile.user.username}}
        </h4>
        <h6 class="card-subtitle text-muted">
            (My profile block)
        </h6>
    </div>
        <img class="responsive" src="{{current_profile.profile_pic}}" alt="Card image">
    <div class="card-block">
        <p class="card-text">
            {{current_profile.bio |truncatechars:25}}
        </p>
        <a href="{% url 'users:user_detail' current_profile.user.pk %}" class="card-link">
            View Your Page
        </a>
        <hr>
        <div class="row count">
            <div class="col-xs-4">
                Tweets
            </div>
            <div class="col-xs-4">
                Followers
            </div>
            <div class="col-xs-4">
                Following
            </div>
        </div>
        <hr>
        <div class="row count">
            <div class="col-xs-4">
                {{current_profile.tweet_set.count}}
            </div>
            <div class="col-xs-4">
                {{current_profile.following.count}}
            </div>
            <div class="col-xs-4">
                {{current_profile.followed_by.count}}
            </div>
        </div>
    </div>
</div>
<div class="card">
    <div class="card-block">
    <div class="row">
    <div class="col-md-12">
        <div >
            <h5>Following</h5>
                {% for a in follows %}
                {% if a %}
                        <a href="{% url 'users:user_detail' a.pk%}" >
                            <img class="responsive-list" src="{{a.profile_pic}}">
                        </a>
                {% endif %}
                {% endfor %}
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div >
            <h5>Followers</h5>
                {% for a in follower %}
                {% if a %}
                        <a href="{% url 'users:user_detail' a.pk%}" >
                            <img class="responsive-list" src="{{a.profile_pic}}">
                        </a>
                {% endif %}
                {% endfor %}
        </div>
    </div>
</div>
    </div>
</div>

users/templates/users/user_detail.html
{% extends "core/base.html" %}
{% block profile-content %}
    {% include "users/profile_block.html" %}
{% endblock profile-content%}
{% block tweet-content %}
{% if user_profile != current_profile %}
    <div class="card">
    <div class="card-block">
        <h4 class="card-title">
            {{user_profile.user.username}}
        </h4>
        <h6 class="card-subtitle text-muted">
            (profile block)
        </h6>
    </div>
        <img class="responsive" src="{{user_profile.profile_pic}}" alt="Card image">
    <div class="card-block">
        <p class="card-text">
            {{user_profile.bio |truncatechars:25}}
        </p>
        <div class="row">
            <div class="col-xs-4">
                Tweets
            </div>
            <div class="col-xs-4">
                Followers
            </div>
            <div class="col-xs-4">
                Following
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-xs-4">
                {{user_profile.tweet_set.count}}
            </div>
            <div class="col-xs-4">
                {{user_profile.following.count}}
            </div>
            <div class="col-xs-4">
                {{user_profile.followed_by.count}}
            </div>
        </div>
    </div>
</div>

{% endif %}
        {% include "tweets/tweet_detail.html" %}
{% endblock tweet-content%}
{% block users-content %}
    {% include "users/other_users.html" %}
{% endblock users-content%}

users/templates/users/user_edit.html
{% extends "core/base.html" %}

{% block content %}
<div class="panel color">
  {% if user %}
<h2>
    Edit:{{user.name}}
</h2>
{% else %}
<h2>
    New User
</h2>
{% endif %}


<form action="" method="POST">
    {% csrf_token %}
    
    {% for field in form %}
    {% include "core/_form_input.html" %}
    {% endfor %}

    <button type="submit" class="btn btn-primary btn-block btn-lg">
        Save
    </button>
</form>  
</div>


{% endblock content %}

users/templates/users/user_list.html
{% extends "core/base.html" %}
{% block profile-content %}
    {% include "users/profile_block.html" %}
{% endblock profile-content%}
{% block tweet-content %}
        {% include "tweets/tweet_list.html" %}
{% endblock tweet-content%}
{% block users-content %}
    {% include "users/other_users.html" %}
{% endblock users-content%}